version: '3.7'

services:
  app:
    container_name: app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    ports:
      - "8080:8000"
